export const CHANGE_CURRENT_SONG = "CHANGE_CURRENT_SONG"
export const CHANGE_CURRENT_SONG_ID = "CHANGE_CURRENT_SONG_ID"
export const CHANGE_PLAY_LIST = "CHANGE_PLAY_LIST"
export const CHANGE_PLAY_SEQUENCE_TYPE = "CHANGE_PLAY_SEQUENCE_TYPE"